### ISSUE TITLE
doesn't work with click

### ISSUE THREAD

**Issue by DetachHead** [jorenham/mainpy#36]
[this example from the docs](https://github.com/jorenham/mainpy?tab=readme-ov-file#click) doesn't seem to work
```py
import mainpy
import click

@mainpy.main
@click.command()
def click_command():
    click.echo('Hello from click_command') # never runs
```
```
python foo.py
```

mainpy v1.3.2 
click v8.1.7
python v3.12

**Comment by jorenham** [comment]
I'm not sure why yet, but when you `from mainpy import main` and `@main` instead, it works again 🤔

**Comment by jorenham** [comment]
This was caused by a bug in `click.core.Command` that doesn't call `functools.update_wrapper` (unlike `click.core.Group`), so that the wrapped function's `__module__` is "overwritten" with `"click.core"`.
