### ISSUE TITLE
`Any` error when using with click

### ISSUE THREAD

**Issue by DetachHead** [jorenham/mainpy#41]
thanks for fixing #36 so quickly

i noticed that both basedpyright and basedmypy report the function as containing `Any` when using the `main` decorator with click

```py
import click
from mainpy import main


@main # basedpyright error: Function decorator obscures type of function because its type is Any (reportAny)
@click.command()
def click_command(): # basedmypy error: no-any-decorated
    print("Hello from click_command")
```

basedpyright 1.17.1
basedmypy 2.6.0

**Comment by DetachHead** [comment]
oh wait, this is an issue with click:

```py
import click


@click.command()
def click_command():
    print("Hello from click_command")


if __name__ == "__main__":
    reveal_type(click_command())  # Any
```

**Comment by jorenham** [comment]
If you wanna have nice annotations, then I could recommend [Typer](https://typer.tiangolo.com/) instead, which builds upon click.
